# Custom Language File for Launcher Customizer

[ejs.app]
title = "MBTI 단합대회"

[ejs.landing]
mediaGitHubURL = "https://ch.sooplive.co.kr/moolchoco"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "#"
mediaAfreecaTVURL = "https://ch.sooplive.co.kr/moolchoco/post/139640487"
screenshotsTooltip = "스크린샷"

[ejs.settings]
sourceGithubLink = "https://github.com/CustomLauncherLab/moolchoco_mbti"
supportLink = "https://github.com/CustomLauncherLab/moolchoco_mbti/issues"

[ejs.welcome]
welcomeHeader = "MBTI 단합대회"
welcomeDescription = ""
welcomeDescCTA = ""
